/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author paola
 */
public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        bienvenida = new javax.swing.JMenu();
        cargarArchivo = new javax.swing.JMenuItem();
        archivoDefault = new javax.swing.JMenuItem();
        mostrarAlmacenes = new javax.swing.JMenu();
        BFS = new javax.swing.JMenuItem();
        DFS = new javax.swing.JMenuItem();
        realizarPedido = new javax.swing.JMenu();
        agregar = new javax.swing.JMenu();
        agregarAlmacen = new javax.swing.JMenuItem();
        agregarRuta = new javax.swing.JMenuItem();
        agregarProducto = new javax.swing.JMenuItem();
        realizarPedido1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 450));

        bienvenida.setText("  Archivos  ");
        bienvenida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bienvenidaActionPerformed(evt);
            }
        });

        cargarArchivo.setText("Cargar Archivo");
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });
        bienvenida.add(cargarArchivo);

        archivoDefault.setText("Archivo Default");
        archivoDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoDefaultActionPerformed(evt);
            }
        });
        bienvenida.add(archivoDefault);

        jMenuBar1.add(bienvenida);

        mostrarAlmacenes.setText("  Mostrar Almacenes  ");
        mostrarAlmacenes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mostrarAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAlmacenesActionPerformed(evt);
            }
        });

        BFS.setText("Recorrido en anchura ");
        BFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFSActionPerformed(evt);
            }
        });
        mostrarAlmacenes.add(BFS);

        DFS.setText("Recorrido en profundidad");
        DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFSActionPerformed(evt);
            }
        });
        mostrarAlmacenes.add(DFS);

        jMenuBar1.add(mostrarAlmacenes);

        realizarPedido.setText("  Realizar Pedido  ");
        realizarPedido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuBar1.add(realizarPedido);

        agregar.setText("  Agregar  ");
        agregar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        agregarAlmacen.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        agregarAlmacen.setText("Agregar Almacén");
        agregarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAlmacenActionPerformed(evt);
            }
        });
        agregar.add(agregarAlmacen);

        agregarRuta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        agregarRuta.setText("Agregar Ruta");
        agregarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarRutaActionPerformed(evt);
            }
        });
        agregar.add(agregarRuta);

        agregarProducto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        agregarProducto.setText("Agregar Producto");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });
        agregar.add(agregarProducto);

        jMenuBar1.add(agregar);

        realizarPedido1.setText("  Mostrar Grafo  ");
        realizarPedido1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuBar1.add(realizarPedido1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAlmacenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarAlmacenesActionPerformed

    private void agregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarRutaActionPerformed
        Ventana5 v5 = new Ventana5();
        v5.setVisible(true);
    }//GEN-LAST:event_agregarRutaActionPerformed

    private void bienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bienvenidaActionPerformed
        
    }//GEN-LAST:event_bienvenidaActionPerformed

    private void agregarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAlmacenActionPerformed
        Ventana4 v4 = new Ventana4();
        v4.setVisible(true);
    }//GEN-LAST:event_agregarAlmacenActionPerformed

    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed
        Grafo grafo = openFile();
        Global.setGrafo(grafo);
        
    }//GEN-LAST:event_cargarArchivoActionPerformed

    private void BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFSActionPerformed
        Global.setPath(1);
        Ventana2 v2 = new Ventana2();
        v2.setVisible(true);
        v2.showStorage();
        
        
        
    }//GEN-LAST:event_BFSActionPerformed

    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSActionPerformed
        Global.setPath(2);
        Ventana2 v2 = new Ventana2();
        v2.setVisible(true);
        v2.showStorage();

        
    }//GEN-LAST:event_DFSActionPerformed

    private void archivoDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoDefaultActionPerformed
        Grafo grafo = txt.readTxt();
        grafo.readRoutes();
        grafo.printMatrix();
        Global.setGrafo(grafo);
        
    }//GEN-LAST:event_archivoDefaultActionPerformed

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        Ventana6 v6 = new Ventana6();
        v6.setVisible(true);
    }//GEN-LAST:event_agregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    
    private Grafo openFile() {
    String aux = "";   
    String text = "";
    Grafo grafo = null;
    try
    {
     JFileChooser jf = new JFileChooser();
     jf.showOpenDialog(this);
     File file = jf.getSelectedFile();
     if(file!=null)
     {     
        FileReader fr = new FileReader(file);
        BufferedReader br = new BufferedReader(fr);
        while((aux=br.readLine())!=null)
        {
           text += aux+ "\n";
        }
           br.close();
           JOptionPane.showMessageDialog(null,"El archivo se abrió exitosamente!");
      }
        grafo = txt.checkFile(text);
        Global.setGrafo(grafo);
//        NO SE SI DEBERIA HACER QUE MEJOR LA FUNCIÓN RETORNE EL GRAFO
        if (grafo != null){
            Ventana1 v1 = new Ventana1();
            v1.setVisible(true);
            return grafo;
        }
     }
     catch(IOException ex)
     {
       JOptionPane.showMessageDialog(null,ex+"" +
             "\nNo se ha encontrado el archivo");
      }
    return grafo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BFS;
    private javax.swing.JMenuItem DFS;
    private javax.swing.JMenu agregar;
    private javax.swing.JMenuItem agregarAlmacen;
    private javax.swing.JMenuItem agregarProducto;
    private javax.swing.JMenuItem agregarRuta;
    private javax.swing.JMenuItem archivoDefault;
    private javax.swing.JMenu bienvenida;
    private javax.swing.JMenuItem cargarArchivo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mostrarAlmacenes;
    private javax.swing.JMenu realizarPedido;
    private javax.swing.JMenu realizarPedido1;
    // End of variables declaration//GEN-END:variables
}
