/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import javax.swing.JOptionPane;

/**
 * Esta clase maneja todas las funcionalidades de la ventana 6, que se encarga de registar los datos del usuario para agregar un nuevo prodcuto
 * @author paola
 */
public class Ventana6 extends javax.swing.JFrame {

    /**
     * Constructor para la ventana 6
     */
    public Ventana6() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        storageProduct = new javax.swing.JTextField();
        newProduct = new javax.swing.JButton();
        addProduct = new javax.swing.JButton();
        nameProduct = new javax.swing.JTextField();
        stockProduct = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("AÑADIR PRODUCTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Nombre del producto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Almacen receptor: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Cantidad del producto: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        storageProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storageProductActionPerformed(evt);
            }
        });
        jPanel1.add(storageProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 90, -1));

        newProduct.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        newProduct.setText("Nuevo");
        newProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductActionPerformed(evt);
            }
        });
        jPanel1.add(newProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        addProduct.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        addProduct.setText("Añadir");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });
        jPanel1.add(addProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        nameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameProductActionPerformed(evt);
            }
        });
        jPanel1.add(nameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 90, -1));

        stockProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockProductActionPerformed(evt);
            }
        });
        jPanel1.add(stockProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Este método toma los input del usuario, y llama a la función que agregará el producto
    */
    private void newProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductActionPerformed
        String productName = nameProduct.getText();
        String storage = storageProduct.getText().toUpperCase();
        String stockP = stockProduct.getText();
        Basket.newProduct(productName, storage, stockP);
    }//GEN-LAST:event_newProductActionPerformed

    private void storageProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storageProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storageProductActionPerformed

    private void nameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameProductActionPerformed

    private void stockProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockProductActionPerformed
    
    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        String productName = nameProduct.getText();
        String storage = storageProduct.getText().toUpperCase();
        int indexStorage = Global.getGrafo().getIndex(storage);
        if(indexStorage != -1){
            Product p = Validation.products(indexStorage, productName);
            if( p != null){
                try{
                    int stock = Integer.parseInt(stockProduct.getText());
                    p.setStock(p.getStock() + stock);
                    JOptionPane.showMessageDialog(null,"Cantidad de producto añadido correctamente"); 
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Error en la cantidad ingresada"); 
                }
            }else{
                JOptionPane.showMessageDialog(null,"Error en el nombre del producto"); 
            }
        }else{
            JOptionPane.showMessageDialog(null,"Error en el nombre del almacen"); 
        }
    }//GEN-LAST:event_addProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameProduct;
    private javax.swing.JButton newProduct;
    private javax.swing.JTextField stockProduct;
    private javax.swing.JTextField storageProduct;
    // End of variables declaration//GEN-END:variables
}
